# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa2e3be3ef29b1dd1a1bea02ef27346976e3f487e4a568135b6db85dd19fc015e6233c8a447b14c1505100b20a7c614e8ee95a60cb4d7d813209816612d3f224

test:
  secret_key_base: 57c3b134eae43f6e883f7b8ab618791007d582cdf9a99e2359c7223cbb707ca32fd6a269667c37466d648b65527e9d17b5fa1221920efb9567f138896cabd771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
